export enum ExceptionsInternalCodes {
  UNKNOWN_SQL_EXCEPTION = 1000,
  DELETE_ROW_FROM_TABLE_EXCEPTION = 1001,
  GET_TABLE_PRIMARY_COLUMNS_EXCEPTION = 1002,
  GET_TABLE_STRUCTURE_EXCEPTION = 1003,
  GET_ROW_BY_PRIMARY_KEY_EXCEPTION = 1004,
  GET_TABLES_EXCEPTION = 1005,
  GET_TABLE_ROWS_EXCEPTION = 1006,
}

