export enum ExceptionsInternalCodes {
  UNKNOWN_SQL_EXCEPTION = 1000,
  GET_TABLE_STRUCTURE_EXCEPTION = 1003,
  GET_ROW_BY_PRIMARY_KEY_EXCEPTION = 1004,
  GET_TABLES_EXCEPTION = 1005,
  GET_TABLE_ROWS_EXCEPTION = 1006,
  VALIDATOR_EXCEPTION = 1007,
}

