export enum SchemaChangeStatusEnum {
	PENDING = 'PENDING',
	APPROVED = 'APPROVED',
	APPLYING = 'APPLYING',
	APPLIED = 'APPLIED',
	FAILED = 'FAILED',
	REJECTED = 'REJECTED',
	ROLLED_BACK = 'ROLLED_BACK',
}

export enum SchemaChangeTypeEnum {
	CREATE_TABLE = 'CREATE_TABLE',
	DROP_TABLE = 'DROP_TABLE',
	ADD_COLUMN = 'ADD_COLUMN',
	DROP_COLUMN = 'DROP_COLUMN',
	ALTER_COLUMN = 'ALTER_COLUMN',
	ADD_INDEX = 'ADD_INDEX',
	DROP_INDEX = 'DROP_INDEX',
	ADD_FOREIGN_KEY = 'ADD_FOREIGN_KEY',
	DROP_FOREIGN_KEY = 'DROP_FOREIGN_KEY',
	ADD_PRIMARY_KEY = 'ADD_PRIMARY_KEY',
	DROP_PRIMARY_KEY = 'DROP_PRIMARY_KEY',
	MONGO_CREATE_COLLECTION = 'MONGO_CREATE_COLLECTION',
	MONGO_DROP_COLLECTION = 'MONGO_DROP_COLLECTION',
	MONGO_SET_VALIDATOR = 'MONGO_SET_VALIDATOR',
	MONGO_CREATE_INDEX = 'MONGO_CREATE_INDEX',
	MONGO_DROP_INDEX = 'MONGO_DROP_INDEX',
	ROLLBACK = 'ROLLBACK',
	OTHER = 'OTHER',
}

export function isMongoSchemaChangeType(changeType: SchemaChangeTypeEnum): boolean {
	return changeType.startsWith('MONGO_');
}
