FROM node:22-slim

RUN groupadd -r appuser && useradd -r -g appuser -d /app -s /sbin/nologin appuser

WORKDIR /app
RUN apt-get update && apt-get install -y netcat-openbsd make gcc g++ python3 libxml2

COPY package.json .yarnrc.yml yarn.lock tsconfig.json /app/
COPY shared-code /app/shared-code
COPY rocketadmin-agent /app/rocketadmin-agent
COPY .yarn /app/.yarn
RUN yarn install --network-timeout 1000000
RUN ./node_modules/.bin/tsc --build
RUN cd rocketadmin-agent && yarn run nest build

RUN chown -R appuser:appuser /app

USER appuser

WORKDIR /app/rocketadmin-agent
CMD ["node", "dist/main.js"]
