export enum ConnectionTypesEnum {
  postgres = 'postgres',
  mysql = 'mysql',
  mysql2 = 'mysql2',
  oracledb = 'oracledb',
  mssql = 'mssql',
  ibmdb2 = 'ibmdb2',
  mongodb = 'mongodb',
  agent_postgres = 'agent_postgres',
  agent_mysql = 'agent_mysql',
  agent_oracledb = 'agent_oracledb',
  agent_mssql = 'agent_mssql',
  agent_ibmdb2 = 'agent_ibmdb2',
  agent_mongodb = 'agent_mongodb',
}
