export enum DataAccessObjectCommandsEnum {
  addRowInTable = 'addRowInTable',
  deleteRowInTable = 'deleteRowInTable',
  getRowByPrimaryKey = 'getRowByPrimaryKey',
  bulkGetRowsFromTableByPrimaryKeys = 'bulkGetRowsFromTableByPrimaryKeys',
  getRowsFromTable = 'getRowsFromTable',
  getTableForeignKeys = 'getTableForeignKeys',
  getTablePrimaryColumns = 'getTablePrimaryColumns',
  getTableStructure = 'getTableStructure',
  getTablesFromDB = 'getTablesFromDB',
  testConnect = 'testConnect',
  updateRowInTable = 'updateRowInTable',
  bulkUpdateRowsInTable = 'bulkUpdateRowsInTable',
  bulkDeleteRowsInTable = 'bulkDeleteRowsInTable',
  validateSettings = 'validateSettings',
  getIdentityColumns = 'getIdentityColumns',
  getReferencedTableNamesAndColumns = 'getReferencedTableNamesAndColumns',
  isView = 'isView',
  getRowsAsStream = 'getRowsAsStream',
  executeRawQuery = 'executeRawQuery',
}
