export enum TableWidgetTypeEnum {
  Password = 'Password',
  Boolean = 'Boolean',
  Date = 'Date',
  Time = 'Time',
  DateTime = 'DateTime',
  JSON = 'JSON',
  Textarea = 'Textarea',
  String = 'String',
  Readonly = 'Readonly',
  Number = 'Number',
  Select = 'Select',
  UUID = 'UUID',
  Enum = 'Enum',
  Foreign_key = 'Foreign_key',
  File = 'File',
  Image = 'Image',
  URL = 'URL',
  Code = 'Code',
  Phone = 'Phone',
  Country = 'Country',
  Color = 'Color',
}
