import { TableStructureDS } from '@rocketadmin/shared-code/src/data-access-layer/shared/data-structures/table-structure.ds.js';
import { Messages } from '../../../exceptions/text/messages.js';

export function validateTableRowUtil(row: Record<string, unknown>, structure: Array<TableStructureDS>): Array<string> {
  const errors = [];
  const keys = Object.keys(row);
  keys.map((key) => {
    key.toLowerCase();
  });

  for (let i = 0; i < structure.length; i++) {
    try {
      const index = keys.indexOf(structure.at(i)['column_name'] || structure.at(i)['COLUMN_NAME']);
      if (
        (index >= 0 &&
          structure.at(i)['column_default'] != null &&
          structure.at(i)['column_default'].includes('nextval')) ||
        (index >= 0 &&
          structure.at(i)['column_default'] != null &&
          structure.at(i)['column_default'].includes('generate'))
      ) {
        errors.push(Messages.CANNOT_ADD_AUTOGENERATED_VALUE);
      }
    } catch (_e) {}
  }
  return errors;
}
