import { TableStructureDS } from '@rocketadmin/shared-code/dist/src/data-access-layer/shared/data-structures/table-structure.ds.js';
import { Messages } from '../../../exceptions/text/messages.js';

export function validateTableRowUtil(row: Record<string, unknown>, structure: Array<TableStructureDS>): Array<string> {
	const errors = [];
	const keys = Object.keys(row).map((key) => key.toLowerCase());

	for (let i = 0; i < structure.length; i++) {
		try {
			const column = structure[i];
			const index = keys.indexOf(column.column_name);
			const columnDefault = column.column_default;
			if (
				index >= 0 &&
				typeof columnDefault === 'string' &&
				(columnDefault.includes('nextval') || columnDefault.includes('generate'))
			) {
				errors.push(Messages.CANNOT_ADD_AUTOGENERATED_VALUE);
			}
		} catch (_e) {}
	}
	return errors;
}
