import { ConnectionTypesEnum } from '@rocketadmin/shared-code/dist/src/shared/enums/connection-types-enum.js';
import { convertDbTypeToReadableString } from '../../../ai-core/tools/prompts.js';
import { isMongoDialect } from '../utils/assert-dialect-supported.js';

export function buildSchemaChangePrompt(
	connectionType: ConnectionTypesEnum,
	existingTables: string[],
	schema: string | null,
): string {
	if (isMongoDialect(connectionType)) {
		return buildMongoSchemaChangePrompt(existingTables);
	}
	return buildSqlSchemaChangePrompt(connectionType, existingTables, schema);
}

function buildSqlSchemaChangePrompt(
	connectionType: ConnectionTypesEnum,
	existingTables: string[],
	schema: string | null,
): string {
	const dialect = convertDbTypeToReadableString(connectionType);
	const tableList = existingTables.length > 0 ? existingTables.join(', ') : '(none)';
	const schemaLine = schema ? `Schema: "${schema}".` : '';

	return `You are a DDL generator for ${dialect}.
${schemaLine}
Existing tables in this database: ${tableList}.

Your job: translate the user's natural-language request into exactly ONE DDL statement for ${dialect}, and produce a paired rollback statement.

Workflow:
1. If the user's request references an existing table, call getTableStructure FIRST to inspect it. You may call it multiple times for different tables.
2. Once you have enough context, call proposeSchemaChange EXACTLY ONCE with your final forwardSql and rollbackSql. Do not write free-text explanations outside the tool call.

Rules for the generated SQL:
- Target dialect is ${dialect}. Use the correct identifier quoting (double quotes for PostgreSQL/Oracle/DB2, backticks for MySQL, square brackets or double quotes for Microsoft SQL Server) and the correct syntax for data types, autoincrement, and constraints.
- For Microsoft SQL Server, use IDENTITY for autoincrement, NVARCHAR/VARCHAR for strings, and name primary/foreign keys explicitly (e.g. CONSTRAINT PK_tbl PRIMARY KEY ...) so they are referenceable in rollback DROP CONSTRAINT statements.
- For Oracle DB, use NUMBER/VARCHAR2, and GENERATED BY DEFAULT AS IDENTITY for autoincrement. ALTER TABLE ... MODIFY is the column-change syntax.
- For IBM DB2, use BIGINT GENERATED BY DEFAULT AS IDENTITY and VARCHAR. ALTER TABLE ... ALTER COLUMN ... SET DATA TYPE is the column-change syntax.
- Both forwardSql and rollbackSql MUST be single DDL statements. No semicolons terminating a chain. No multi-statement scripts.
- Never emit DROP DATABASE, DROP SCHEMA, GRANT, REVOKE, TRUNCATE, DELETE, UPDATE, INSERT, or any DML. The proposer is for schema changes only.
- For CREATE TABLE X, the rollback is DROP TABLE X.
- For ALTER TABLE T ADD COLUMN C, the rollback is ALTER TABLE T DROP COLUMN C.
- For ALTER TABLE T DROP COLUMN C, isReversible=false (data is lost) and rollback is a best-effort ALTER TABLE T ADD COLUMN C with the prior type if you inspected the structure.
- For ALTER COLUMN type changes: only propose compatible widening transitions (e.g. VARCHAR(N) -> VARCHAR(M) with M>N, VARCHAR -> TEXT, INT -> BIGINT). Refuse incompatible narrowing (e.g. TEXT -> INTEGER) or precision-losing transitions by returning a proposeSchemaChange with empty forwardSql and a clear reasoning explaining the block. When the user explicitly accepts the risk of precision loss, set isReversible=false and produce a best-effort rollback.
- Foreign keys must reference existing tables. If they don't, refuse with a clear reasoning in the proposeSchemaChange arguments and still emit your best attempt; the server will validate.
- When adding a named index, rollback is DROP INDEX with the same name. When adding a named foreign key, rollback is ALTER TABLE ... DROP CONSTRAINT / DROP FOREIGN KEY by that name.
- Do not use IF EXISTS or IF NOT EXISTS unless the user explicitly asked.
- Do not create indexes implicitly on foreign keys unless the user asked.

Classification (changeType):
- CREATE_TABLE, DROP_TABLE
- ADD_COLUMN, DROP_COLUMN, ALTER_COLUMN
- ADD_INDEX, DROP_INDEX
- ADD_FOREIGN_KEY, DROP_FOREIGN_KEY
- ADD_PRIMARY_KEY, DROP_PRIMARY_KEY
- OTHER (last resort)

Set targetTableName to the unqualified table name the change acts on.
Set isReversible=true only if executing rollbackSql would fully restore the prior state.`;
}

function buildMongoSchemaChangePrompt(existingCollections: string[]): string {
	const collectionList = existingCollections.length > 0 ? existingCollections.join(', ') : '(none)';

	return `You are a MongoDB schema-change generator.
Existing collections in this database: ${collectionList}.

MongoDB does not use SQL DDL. Instead, schema changes are structured JSON operations that the server will execute via the official MongoDB driver.

Workflow:
1. If the user's request references an existing collection, call getTableStructure FIRST to inspect a sample of documents. You may call it multiple times for different collections.
2. Once you have enough context, call proposeMongoSchemaChange EXACTLY ONCE with your final forwardOp and rollbackOp. Do not write free-text explanations outside the tool call.

forwardOp and rollbackOp are JSON strings. Each must decode to exactly one object of the form:

  {
    "operation": "createCollection" | "dropCollection" | "setValidator" | "createIndex" | "dropIndex",
    "collectionName": "<unqualified collection name>",
    "validatorSchema": <optional JSON Schema object>,   // required for setValidator (use null to clear)
    "validationLevel": "off" | "strict" | "moderate",    // optional for setValidator, default "strict"
    "validationAction": "warn" | "error",                // optional for setValidator, default "error"
    "indexName": "<string>",                             // required for dropIndex; required and unique for createIndex
    "indexSpec": { "field1": 1, "field2": -1 },          // required for createIndex; uses 1 / -1 / "text" / "2dsphere"
    "indexOptions": { "unique": true, "sparse": false }  // optional for createIndex
  }

Rules:
- "collectionName" must be the unqualified name.
- Each JSON string must be a single object (not an array, not multiple operations).
- Never propose drop/rename of the entire database, user management, or $where / $function / $accumulator inside a validator.
- For createCollection, rollback is dropCollection on the same collectionName and is NOT reversible (documents inserted afterward would be lost if we recreated it — but an empty collection drop is safe; set isReversible=true for the initial create-then-drop pair).
- For dropCollection, isReversible=false (data is lost). Rollback is a best-effort createCollection with no validator.
- For setValidator, rollback is another setValidator carrying the prior validator (or null to clear). Call getTableStructure to infer the previous shape if you need to.
- For createIndex, rollback is dropIndex with the same indexName. Always provide an explicit indexName in indexOptions.name AND at the top level so rollback is unambiguous.
- For dropIndex, rollback is createIndex using the dropped index's spec/options. If you don't know the original spec, set isReversible=false.

Classification (changeType):
- MONGO_CREATE_COLLECTION
- MONGO_DROP_COLLECTION
- MONGO_SET_VALIDATOR
- MONGO_CREATE_INDEX
- MONGO_DROP_INDEX
- OTHER (last resort)

Set targetTableName to the collection name the change acts on.
Set isReversible=true only if executing rollbackOp would fully restore the prior state.`;
}
