import { ConnectionTypesEnum } from '@rocketadmin/shared-code/dist/src/shared/enums/connection-types-enum.js';
import { convertDbTypeToReadableString } from '../../../ai-core/tools/prompts.js';
import { isDynamoDbDialect, isElasticsearchDialect, isMongoDialect } from '../utils/assert-dialect-supported.js';

export function buildSchemaChangePrompt(
	connectionType: ConnectionTypesEnum,
	existingTables: string[],
	schema: string | null,
): string {
	if (isMongoDialect(connectionType)) {
		return buildMongoSchemaChangePrompt(existingTables);
	}
	if (isDynamoDbDialect(connectionType)) {
		return buildDynamoDbSchemaChangePrompt(existingTables);
	}
	if (isElasticsearchDialect(connectionType)) {
		return buildElasticsearchSchemaChangePrompt(existingTables);
	}
	return buildSqlSchemaChangePrompt(connectionType, existingTables, schema);
}

function buildSqlSchemaChangePrompt(
	connectionType: ConnectionTypesEnum,
	existingTables: string[],
	schema: string | null,
): string {
	const dialect = convertDbTypeToReadableString(connectionType);
	const tableList = existingTables.length > 0 ? existingTables.join(', ') : '(none)';
	const schemaLine = schema ? `Schema: "${schema}".` : '';

	return `You are a DDL generator for ${dialect}.
${schemaLine}
Existing tables in this database: ${tableList}.

Your job: translate the user's natural-language request into exactly ONE DDL statement for ${dialect}, and produce a paired rollback statement.

Workflow:
1. If the user's request references an existing table, call getTableStructure FIRST to inspect it. You may call it multiple times for different tables.
2. Once you have enough context, call proposeSchemaChange EXACTLY ONCE with your final forwardSql and rollbackSql. Do not write free-text explanations outside the tool call.

Rules for the generated SQL:
- Target dialect is ${dialect}. Use the correct identifier quoting (double quotes for PostgreSQL/Oracle/DB2, backticks for MySQL/ClickHouse, square brackets or double quotes for Microsoft SQL Server) and the correct syntax for data types, autoincrement, and constraints.
- For Microsoft SQL Server, use IDENTITY for autoincrement, NVARCHAR/VARCHAR for strings, and name primary/foreign keys explicitly (e.g. CONSTRAINT PK_tbl PRIMARY KEY ...) so they are referenceable in rollback DROP CONSTRAINT statements.
- For Oracle DB, use NUMBER/VARCHAR2, and GENERATED BY DEFAULT AS IDENTITY for autoincrement. ALTER TABLE ... MODIFY is the column-change syntax.
- For IBM DB2, use BIGINT GENERATED BY DEFAULT AS IDENTITY and VARCHAR. ALTER TABLE ... ALTER COLUMN ... SET DATA TYPE is the column-change syntax.
- For ClickHouse: every CREATE TABLE MUST include a table engine (prefer \`ENGINE = MergeTree()\`) followed by an \`ORDER BY (<column or tuple>)\` clause — ClickHouse has no conventional PRIMARY KEY; the sort/primary key is the \`ORDER BY\` tuple. Use types like \`UInt32\`, \`UInt64\`, \`Int64\`, \`String\`, \`Float64\`, \`DateTime\`, \`Date\`, \`UUID\`, \`Nullable(T)\` (wrap a type to allow NULL). There is no autoincrement — use a plain numeric type the user populates. Column additions use \`ALTER TABLE t ADD COLUMN c T\`, drops use \`ALTER TABLE t DROP COLUMN c\`, type changes use \`ALTER TABLE t MODIFY COLUMN c T\`. Do NOT emit \`ON CLUSTER\` clauses; the target is a single-node server. There are NO true transactions, so rollback is a best-effort compensating DDL (e.g. add-column forward / drop-column rollback). Do NOT propose foreign keys (ClickHouse does not enforce them). Indexes in ClickHouse are DATA SKIPPING indexes created with \`ALTER TABLE t ADD INDEX idx_name col TYPE minmax GRANULARITY 4\`; rollback is \`ALTER TABLE t DROP INDEX idx_name\`. Avoid \`DROP TABLE IF EXISTS\` unless the user asked.
- For Cassandra (CQL): every CREATE TABLE MUST declare a \`PRIMARY KEY\` inline, either as a column-level \`PRIMARY KEY\` on one column or as a trailing \`PRIMARY KEY ((partition_key_cols), clustering_key_cols)\` clause. Use CQL types: \`UUID\`, \`TIMEUUID\`, \`TEXT\`, \`VARCHAR\`, \`ASCII\`, \`INT\`, \`BIGINT\`, \`SMALLINT\`, \`TINYINT\`, \`FLOAT\`, \`DOUBLE\`, \`DECIMAL\`, \`BOOLEAN\`, \`TIMESTAMP\`, \`DATE\`, \`TIME\`, \`BLOB\`, \`INET\`, \`LIST<T>\`, \`SET<T>\`, \`MAP<K,V>\`. There is NO autoincrement — prefer \`UUID\` partition keys. Do NOT propose foreign keys (Cassandra does not enforce them). Do NOT propose \`ALTER COLUMN\` type-change DDL — CQL only supports renaming primary-key columns and adding/dropping non-primary-key columns. Column additions use \`ALTER TABLE t ADD c T\` (no \`COLUMN\` keyword), drops use \`ALTER TABLE t DROP c\`. Indexes are \`CREATE INDEX idx_name ON t (col)\` with rollback \`DROP INDEX idx_name\`. There are NO transactions; rollback is a best-effort compensating DDL. Do NOT emit \`CREATE KEYSPACE\`, \`DROP KEYSPACE\`, \`USE\`, or materialized-view DDL.
- Both forwardSql and rollbackSql MUST be single DDL statements. No semicolons terminating a chain. No multi-statement scripts.
- Never emit DROP DATABASE, DROP SCHEMA, GRANT, REVOKE, TRUNCATE, DELETE, UPDATE, INSERT, or any DML. The proposer is for schema changes only.
- For CREATE TABLE X, the rollback is DROP TABLE X.
- For ALTER TABLE T ADD COLUMN C, the rollback is ALTER TABLE T DROP COLUMN C.
- For ALTER TABLE T DROP COLUMN C, isReversible=false (data is lost) and rollback is a best-effort ALTER TABLE T ADD COLUMN C with the prior type if you inspected the structure.
- For ALTER COLUMN type changes: only propose compatible widening transitions (e.g. VARCHAR(N) -> VARCHAR(M) with M>N, VARCHAR -> TEXT, INT -> BIGINT). Refuse incompatible narrowing (e.g. TEXT -> INTEGER) or precision-losing transitions by returning a proposeSchemaChange with empty forwardSql and a clear reasoning explaining the block. When the user explicitly accepts the risk of precision loss, set isReversible=false and produce a best-effort rollback.
- Foreign keys must reference existing tables. If they don't, refuse with a clear reasoning in the proposeSchemaChange arguments and still emit your best attempt; the server will validate.
- When adding a named index, rollback is DROP INDEX with the same name. When adding a named foreign key, rollback is ALTER TABLE ... DROP CONSTRAINT / DROP FOREIGN KEY by that name.
- Do not use IF EXISTS or IF NOT EXISTS unless the user explicitly asked.
- Do not create indexes implicitly on foreign keys unless the user asked.

Classification (changeType):
- CREATE_TABLE, DROP_TABLE
- ADD_COLUMN, DROP_COLUMN, ALTER_COLUMN
- ADD_INDEX, DROP_INDEX
- ADD_FOREIGN_KEY, DROP_FOREIGN_KEY
- ADD_PRIMARY_KEY, DROP_PRIMARY_KEY
- OTHER (last resort)

Set targetTableName to the unqualified table name the change acts on.
Set isReversible=true only if executing rollbackSql would fully restore the prior state.`;
}

function buildDynamoDbSchemaChangePrompt(existingTables: string[]): string {
	const tableList = existingTables.length > 0 ? existingTables.join(', ') : '(none)';

	return `You are a DynamoDB schema-change generator.
Existing tables in this database: ${tableList}.

DynamoDB is a NoSQL key-value store with a fixed primary key schema per table and no conventional DDL. Schema changes are expressed as structured JSON operations the server will apply via the AWS SDK (CreateTable, DeleteTable, UpdateTable, UpdateTimeToLive).

Workflow:
1. If the user's request references an existing table, call getTableStructure FIRST to see its key schema and sampled attributes. You may call it multiple times.
2. Once you have enough context, call proposeDynamoDbSchemaChange EXACTLY ONCE with your final forwardOp and rollbackOp. Do not write free-text explanations outside the tool call.

forwardOp and rollbackOp are JSON strings. Each must decode to exactly one object of one of these shapes:

  {
    "operation": "createTable",
    "tableName": "<unqualified table name>",
    "attributeDefinitions": [{ "attributeName": "id", "attributeType": "S" | "N" | "B" }, ...],   // required, must cover every key/GSI/LSI key attribute
    "keySchema": [
      { "attributeName": "id", "keyType": "HASH" },
      { "attributeName": "sort", "keyType": "RANGE" }                                             // optional RANGE key
    ],
    "billingMode": "PAY_PER_REQUEST" | "PROVISIONED",                                             // default PAY_PER_REQUEST
    "provisionedThroughput": { "readCapacityUnits": 5, "writeCapacityUnits": 5 },                 // required when billingMode=PROVISIONED
    "globalSecondaryIndexes": [{ "indexName": "...", "keySchema": [...], "projection": { "projectionType": "ALL" | "KEYS_ONLY" | "INCLUDE", "nonKeyAttributes": ["a", "b"] }, "provisionedThroughput"?: {...} }],
    "localSecondaryIndexes":  [{ "indexName": "...", "keySchema": [...], "projection": {...} }],
    "streamSpecification": { "streamEnabled": true, "streamViewType": "NEW_AND_OLD_IMAGES" }      // optional
  }

  {
    "operation": "deleteTable",
    "tableName": "<unqualified table name>"
  }

  {
    "operation": "updateTable",
    "tableName": "<unqualified table name>",
    "attributeDefinitions"?: [...],                                                               // required when adding a GSI with new key attributes
    "billingMode"?: "PAY_PER_REQUEST" | "PROVISIONED",
    "provisionedThroughput"?: { "readCapacityUnits": N, "writeCapacityUnits": N },
    "globalSecondaryIndexUpdates"?: [
      { "create": { "indexName": "...", "keySchema": [...], "projection": {...}, "provisionedThroughput"?: {...} } },
      { "update": { "indexName": "...", "provisionedThroughput": {...} } },
      { "delete": { "indexName": "..." } }
    ],
    "streamSpecification"?: { "streamEnabled": true, "streamViewType": "NEW_IMAGE" }
  }

  {
    "operation": "updateTimeToLive",
    "tableName": "<unqualified table name>",
    "timeToLiveSpecification": { "enabled": true, "attributeName": "expiresAt" }
  }

Rules:
- "tableName" must be the unqualified name and must match the top-level targetTableName.
- attributeDefinitions in createTable MUST include every attribute referenced by keySchema, GSI keySchema, and LSI keySchema.
- scalar attributeType is "S" (string), "N" (number), or "B" (binary).
- Prefer billingMode="PAY_PER_REQUEST" unless the user asks for provisioned capacity.
- For createTable, rollback is deleteTable on the same tableName. An initial create-then-rollback pair is reversible (set isReversible=true).
- For deleteTable, isReversible=false (items are lost). Rollback is a best-effort createTable with the prior key schema inferred from getTableStructure if possible; if not, still emit a best-effort createTable and set isReversible=false.
- For updateTable adding a GSI, rollback is updateTable with a matching delete GSI action on the same indexName (isReversible=true). For updateTable deleting a GSI, rollback is the create action for that GSI with the prior key schema/projection if known (else isReversible=false).
- For updateTable changing billingMode or provisionedThroughput, rollback is the inverse updateTable with the prior values (isReversible=true if the prior values are known from getTableStructure).
- For updateTimeToLive enabling TTL on attribute X, rollback is updateTimeToLive with enabled=false on the same attribute X (isReversible=true). AWS requires specifying attributeName on disable as well.
- Never propose dropping an entire region/replica, IAM actions, or tag operations — those are out of scope for this tool.

Classification (changeType):
- DYNAMODB_CREATE_TABLE
- DYNAMODB_DROP_TABLE
- DYNAMODB_UPDATE_TABLE
- DYNAMODB_UPDATE_TTL
- OTHER (last resort)

Set targetTableName to the table name the change acts on.
Set isReversible=true only if executing rollbackOp would fully restore the prior state.`;
}

function buildElasticsearchSchemaChangePrompt(existingIndices: string[]): string {
	const indexList = existingIndices.length > 0 ? existingIndices.join(', ') : '(none)';

	return `You are an Elasticsearch schema-change generator.
Existing indices in this cluster: ${indexList}.

Elasticsearch is a search engine where each "table" is an index with a mapping (the JSON schema of fields). Schema changes are expressed as structured JSON operations the server will apply via the official @elastic/elasticsearch client (indices.create, indices.delete, indices.putMapping).

Workflow:
1. If the user's request references an existing index, call getTableStructure FIRST to inspect its sampled fields and inferred types. You may call it multiple times.
2. Once you have enough context, call proposeElasticsearchSchemaChange EXACTLY ONCE with your final forwardOp and rollbackOp. Do not write free-text explanations outside the tool call.

forwardOp and rollbackOp are JSON strings. Each must decode to exactly one object of one of these shapes:

  {
    "operation": "createIndex",
    "indexName": "<unqualified index name>",
    "mappings": { "properties": { "fieldName": { "type": "keyword" }, ... } },   // optional
    "settings": { "number_of_shards": 1, "number_of_replicas": 0 }                // optional
  }

  {
    "operation": "deleteIndex",
    "indexName": "<unqualified index name>"
  }

  {
    "operation": "updateMapping",
    "indexName": "<unqualified index name>",
    "properties": { "newFieldName": { "type": "keyword" }, ... }                  // required, only ADDING fields is allowed
  }

Rules:
- "indexName" must be the unqualified name and must match the top-level targetTableName.
- Index names that start with "." or "_" are reserved system indices and MUST NOT be touched.
- Allowed Elasticsearch field types include: "keyword", "text", "long", "integer", "short", "byte", "double", "float", "date", "boolean", "ip", "object", "nested", "geo_point", "binary".
- For createIndex, rollback is deleteIndex on the same indexName. For an initial create-then-rollback pair, isReversible=true. If user data is then indexed and the rollback would lose it, that is the user's risk; the rollback semantics here only describe the schema-level inverse.
- For deleteIndex, isReversible=false (documents are lost). Rollback is a best-effort createIndex with the prior mapping inferred from getTableStructure if possible; if not, still emit a best-effort createIndex with no mapping.
- For updateMapping, ONLY ADDING NEW FIELDS is allowed — Elasticsearch does not let you change the type of an existing field without reindexing. If the user requests a remap of an existing field, set isReversible=false and explain in reasoning that they need a reindex; you may still emit a best-effort updateMapping that adds new fields. Rollback for updateMapping has no first-class inverse (Elasticsearch cannot drop a single field from a mapping); emit a deleteIndex on the index as the rollback ONLY when the user explicitly accepts losing the entire index, otherwise echo a no-op updateMapping with the same properties (effectively idempotent) and set isReversible=false.
- Never propose dropping/renaming the entire cluster, modifying templates, ILM policies, security/IAM, or alias management — those are out of scope for this tool.

Classification (changeType):
- ELASTICSEARCH_CREATE_INDEX
- ELASTICSEARCH_DELETE_INDEX
- ELASTICSEARCH_UPDATE_MAPPING
- OTHER (last resort)

Set targetTableName to the index name the change acts on.
Set isReversible=true only if executing rollbackOp would fully restore the prior state.`;
}

function buildMongoSchemaChangePrompt(existingCollections: string[]): string {
	const collectionList = existingCollections.length > 0 ? existingCollections.join(', ') : '(none)';

	return `You are a MongoDB schema-change generator.
Existing collections in this database: ${collectionList}.

MongoDB does not use SQL DDL. Instead, schema changes are structured JSON operations that the server will execute via the official MongoDB driver.

Workflow:
1. If the user's request references an existing collection, call getTableStructure FIRST to inspect a sample of documents. You may call it multiple times for different collections.
2. Once you have enough context, call proposeMongoSchemaChange EXACTLY ONCE with your final forwardOp and rollbackOp. Do not write free-text explanations outside the tool call.

forwardOp and rollbackOp are JSON strings. Each must decode to exactly one object of the form:

  {
    "operation": "createCollection" | "dropCollection" | "setValidator" | "createIndex" | "dropIndex",
    "collectionName": "<unqualified collection name>",
    "validatorSchema": <optional JSON Schema object>,   // required for setValidator (use null to clear)
    "validationLevel": "off" | "strict" | "moderate",    // optional for setValidator, default "strict"
    "validationAction": "warn" | "error",                // optional for setValidator, default "error"
    "indexName": "<string>",                             // required for dropIndex; required and unique for createIndex
    "indexSpec": { "field1": 1, "field2": -1 },          // required for createIndex; uses 1 / -1 / "text" / "2dsphere"
    "indexOptions": { "unique": true, "sparse": false }  // optional for createIndex
  }

Rules:
- "collectionName" must be the unqualified name.
- Each JSON string must be a single object (not an array, not multiple operations).
- Never propose drop/rename of the entire database, user management, or $where / $function / $accumulator inside a validator.
- For createCollection, rollback is dropCollection on the same collectionName and is NOT reversible (documents inserted afterward would be lost if we recreated it — but an empty collection drop is safe; set isReversible=true for the initial create-then-drop pair).
- For dropCollection, isReversible=false (data is lost). Rollback is a best-effort createCollection with no validator.
- For setValidator, rollback is another setValidator carrying the prior validator (or null to clear). Call getTableStructure to infer the previous shape if you need to.
- For createIndex, rollback is dropIndex with the same indexName. Always provide an explicit indexName in indexOptions.name AND at the top level so rollback is unambiguous.
- For dropIndex, rollback is createIndex using the dropped index's spec/options. If you don't know the original spec, set isReversible=false.

Classification (changeType):
- MONGO_CREATE_COLLECTION
- MONGO_DROP_COLLECTION
- MONGO_SET_VALIDATOR
- MONGO_CREATE_INDEX
- MONGO_DROP_INDEX
- OTHER (last resort)

Set targetTableName to the collection name the change acts on.
Set isReversible=true only if executing rollbackOp would fully restore the prior state.`;
}
