export enum AmplitudeEventTypeEnum {
  connectionUpdated = 'Autoadmin_Backend: Connection was updated',
  connectionDeleted = 'Autoadmin_Backend: Connection was deleted',
  connectionReceived = 'Autoadmin_Backend: Connections received',
  connectionUsersReceived = 'Autoadmin_Backend: Connection users list received',
  connectionListReceived = 'Autoadmin_Backend: Connections list received',
  groupListReceived = 'Autoadmin_Backend: Groups list received',
  groupDeleted = 'Autoadmin_Backend: Group deleted',
  groupUserAdded = 'Autoadmin_Backend: User added in group',
  groupUserRemoved = 'Autoadmin_Backend: User removed from group',
  groupUserListReceived = 'Autoadmin_Backend: Group users list received',
  tableListReceived = 'Autoadmin_Backend: Tables list received',
  tableRowsReceived = 'Autoadmin_Backend: Table rows received',
  tableRowReceived = 'Autoadmin_Backend: Table row received',
  tableRowAdded = 'Autoadmin_Backend: Table row added',
  tableRowDeleted = 'Autoadmin_Backend: Table row deleted',

  connectionUpdatedTest = 'Autoadmin_Backend_Test: Connection was updated',
  connectionDeletedTest = 'Autoadmin_Backend_Test: Connection was deleted',
  connectionReceivedTest = 'Autoadmin_Backend_Test: Connections received',
  connectionUsersReceivedTest = 'Autoadmin_Backend_Test: Connection users list received',
  tableListReceivedTest = 'Autoadmin_Backend_Test: Tables list received',
  tableRowsReceivedTest = 'Autoadmin_Backend_Test: Table rows received',
  tableRowReceivedTest = 'Autoadmin_Backend_Test: Table row received',
  tableRowAddedTest = 'Autoadmin_Backend_Test: Table row added',
  tableRowDeletedTest = 'Autoadmin_Backend_Test: Table row deleted',
}
