export enum ConnectionTypeTestEnum {
  postgres = 'postgres',
  mysql = 'mysql',
  mysql2 = 'mysql2',
  oracledb = 'oracledb',
  mssql = 'mssql',
  ibmdb2 = 'ibmdb2',
  mongodb = 'mongodb',
  dynamodb = 'dynamodb',
  agent_postgres = 'agent_postgres',
  agent_mysql = 'agent_mysql',
  agent_oracledb = 'agent_oracledb',
  agent_mssql = 'agent_mssql',
  agent_ibmdb2 = 'agent_ibmdb2',
  agent_mongodb = 'agent_mongodb',
  cli_postgres = 'cli_postgres',
  cli_mysql = 'cli_mysql',
  cli_oracledb = 'cli_oracledb',
  cli_mssql = 'cli_mssql',
  cli_ibmdb2 = 'cli_ibmdb2',
  cli_mongodb = 'cli_mongodb',
}
