export enum SubscriptionLevelEnum {
  FREE_PLAN = 'FREE_PLAN',
  TEAM_PLAN = 'TEAM_PLAN',
  ENTERPRISE_PLAN = 'ENTERPRISE_PLAN',
  ANNUAL_TEAM_PLAN = 'ANNUAL_TEAM_PLAN',
  ANNUAL_ENTERPRISE_PLAN = 'ANNUAL_ENTERPRISE_PLAN',
}
