import { Repository } from 'typeorm';
import { IAgentRepository } from '../../entities/agent/repository/agent.repository.interface.js';
import { IAiResponsesToUserRepository } from '../../entities/ai/ai-data-entities/ai-reponses-to-user/ai-responses-to-user-repository.interface.js';
import { AiResponsesToUserEntity } from '../../entities/ai/ai-data-entities/ai-reponses-to-user/ai-responses-to-user.entity.js';
import { UserApiKeyEntity } from '../../entities/api-key/api-key.entity.js';
import { IUserApiKeyRepository } from '../../entities/api-key/repository/user-api-key-repository.interface.js';
import { CompanyFaviconEntity } from '../../entities/company-favicon/company-favicon.entity.js';
import { CompanyInfoEntity } from '../../entities/company-info/company-info.entity.js';
import { InvitationInCompanyEntity } from '../../entities/company-info/invitation-in-company/invitation-in-company.entity.js';
import { IInvitationInCompanyRepository } from '../../entities/company-info/invitation-in-company/repository/invitation-repository.interface.js';
import { ICompanyInfoRepository } from '../../entities/company-info/repository/company-info-repository.interface.js';
import { CompanyLogoEntity } from '../../entities/company-logo/company-logo.entity.js';
import { CompanyTabTitleEntity } from '../../entities/company-tab-title/company-tab-title.entity.js';
import { IConnectionPropertiesRepository } from '../../entities/connection-properties/repository/connection-properties.repository.interface.js';
import { ConnectionEntity } from '../../entities/connection/connection.entity.js';
import { IConnectionRepository } from '../../entities/connection/repository/connection.repository.interface.js';
import { ICustomFieldsRepository } from '../../entities/custom-field/repository/custom-fields-repository.interface.js';
import { IEmailVerificationRepository } from '../../entities/email/repository/email-verification.repository.interface.js';
import { IGroupRepository } from '../../entities/group/repository/group.repository.interface.js';
import { ILogOutRepository } from '../../entities/log-out/repository/log-out-repository.interface.js';
import { IPermissionRepository } from '../../entities/permission/repository/permission.repository.interface.js';
import { ActionEventsEntity } from '../../entities/table-actions/table-action-events-module/action-event.entity.js';
import { IActionEventsRepository } from '../../entities/table-actions/table-action-events-module/repository/action-events-custom-repository.interface.js';
import { ActionRulesEntity } from '../../entities/table-actions/table-action-rules-module/action-rules.entity.js';
import { IActionRulesRepository } from '../../entities/table-actions/table-action-rules-module/repository/action-rules-custom-repository.interface.js';
import { ITableActionRepository } from '../../entities/table-actions/table-actions-module/repository/table-action-custom-repository.interface.js';
import { TableActionEntity } from '../../entities/table-actions/table-actions-module/table-action.entity.js';
import { TableFieldInfoEntity } from '../../entities/table-field-info/table-field-info.entity.js';
import { ITableFiltersCustomRepository } from '../../entities/table-filters/repository/table-filters-custom-repository.interface.js';
import { TableFiltersEntity } from '../../entities/table-filters/table-filters.entity.js';
import { TableInfoEntity } from '../../entities/table-info/table-info.entity.js';
import { ITableLogsRepository } from '../../entities/table-logs/repository/table-logs-repository.interface.js';
import { ITableSettingsRepository } from '../../entities/table-settings/repository/table-settings.repository.interface.js';
import { TableSettingsEntity } from '../../entities/table-settings/table-settings.entity.js';
import { IUserAccessRepository } from '../../entities/user-access/repository/user-access.repository.interface.js';
import { IUserActionRepository } from '../../entities/user-actions/repository/user-action.repository.interface.js';
import { IUserRepository } from '../../entities/user/repository/user.repository.interface.js';
import { IEmailChangeRepository } from '../../entities/user/user-email/repository/email-change.repository.interface.js';
import { IUserGitHubIdentifierRepository } from '../../entities/user/user-github-identifier/repository/user-github-identifier-repository.interface.js';
import { IUserInvitationRepository } from '../../entities/user/user-invitation/repository/user-invitation-repository.interface.js';
import { IPasswordResetRepository } from '../../entities/user/user-password/repository/password-reset-repository.interface.js';
import { IUserSessionSettings } from '../../entities/user/user-session-settings/reposiotory/user-session-settings-repository.interface.js';
import { UserSessionSettingsEntity } from '../../entities/user/user-session-settings/user-session-settings.entity.js';
import { UserEntity } from '../../entities/user/user.entity.js';
import { ITableWidgetsRepository } from '../../entities/widget/repository/table-widgets-repository.interface.js';
import { TableWidgetEntity } from '../../entities/widget/table-widget.entity.js';
import { IDatabaseContext } from '../database-context.interface.js';
import { TableCategoriesEntity } from '../../entities/table-categories/table-categories.entity.js';
import { ITableCategoriesCustomRepository } from '../../entities/table-categories/repository/table-categories-repository.interface.js';
import { ConnectionPropertiesEntity } from '../../entities/connection-properties/connection-properties.entity.js';
import { UserSecretEntity } from '../../entities/user-secret/user-secret.entity.js';
import { IUserSecretRepository } from '../../entities/user-secret/repository/user-secret-repository.interface.js';
import { SecretAccessLogEntity } from '../../entities/secret-access-log/secret-access-log.entity.js';
import { ISecretAccessLogRepository } from '../../entities/secret-access-log/repository/secret-access-log-repository.interface.js';
import { SignInAuditEntity } from '../../entities/user-sign-in-audit/sign-in-audit.entity.js';
import { ISignInAuditRepository } from '../../entities/user-sign-in-audit/repository/sign-in-audit-repository.interface.js';

export interface IGlobalDatabaseContext extends IDatabaseContext {
  userRepository: Repository<UserEntity> & IUserRepository;
  connectionRepository: Repository<ConnectionEntity> & IConnectionRepository;
  groupRepository: IGroupRepository;
  permissionRepository: IPermissionRepository;
  tableSettingsRepository: Repository<TableSettingsEntity> & ITableSettingsRepository;
  userAccessRepository: IUserAccessRepository;
  agentRepository: IAgentRepository;
  emailVerificationRepository: IEmailVerificationRepository;
  passwordResetRepository: IPasswordResetRepository;
  emailChangeRepository: IEmailChangeRepository;
  userInvitationRepository: IUserInvitationRepository;
  connectionPropertiesRepository: Repository<ConnectionPropertiesEntity> & IConnectionPropertiesRepository;
  customFieldsRepository: ICustomFieldsRepository;
  tableLogsRepository: ITableLogsRepository;
  userActionRepository: IUserActionRepository;
  logOutRepository: ILogOutRepository;
  tableWidgetsRepository: Repository<TableWidgetEntity> & ITableWidgetsRepository;
  tableInfoRepository: Repository<TableInfoEntity>;
  tableFieldInfoRepository: Repository<TableFieldInfoEntity>;
  tableActionRepository: Repository<TableActionEntity> & ITableActionRepository;
  userGitHubIdentifierRepository: IUserGitHubIdentifierRepository;
  companyInfoRepository: Repository<CompanyInfoEntity> & ICompanyInfoRepository;
  invitationInCompanyRepository: Repository<InvitationInCompanyEntity> & IInvitationInCompanyRepository;
  userSessionSettingsRepository: Repository<UserSessionSettingsEntity> & IUserSessionSettings;
  actionRulesRepository: Repository<ActionRulesEntity> & IActionRulesRepository;
  actionEventsRepository: Repository<ActionEventsEntity> & IActionEventsRepository;
  userApiKeysRepository: Repository<UserApiKeyEntity> & IUserApiKeyRepository;
  companyLogoRepository: Repository<CompanyLogoEntity>;
  companyFaviconRepository: Repository<CompanyFaviconEntity>;
  companyTabTitleRepository: Repository<CompanyTabTitleEntity>;
  tableFiltersRepository: Repository<TableFiltersEntity> & ITableFiltersCustomRepository;
  aiResponsesToUserRepository: Repository<AiResponsesToUserEntity> & IAiResponsesToUserRepository;
  tableCategoriesRepository: Repository<TableCategoriesEntity> & ITableCategoriesCustomRepository;
  userSecretRepository: Repository<UserSecretEntity> & IUserSecretRepository;
  secretAccessLogRepository: Repository<SecretAccessLogEntity> & ISecretAccessLogRepository;
  signInAuditRepository: Repository<SignInAuditEntity> & ISignInAuditRepository;
}
