name: frontend
on:
  push:
    branches:
    - main
    # Publish semver tags as releases
    tags: [ '*.*.*' ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd frontend && yarn install
      - name: run tests
        run: cd frontend && yarn test --browsers=ChromeHeadlessCustom --no-watch --no-progress
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: extractions/setup-just@v1
      - name: license checker
        run: 'cd frontend && npx license-checker --onlyAllow="MIT;ISC;Python-2.0;Apache-2.0;BSD;MPL;CC;Custom: http://github.com/dscape/statsd-parser;" --excludePrivatePackages'
